/** Source of truth. Regenerate tokens.css with `pnpm --filter @firmivra/ui tokens`. */
export const tokens = {
  palettes: {
    firmivra: {
      navy: '#001B36',
      navyRaised: '#103F63',
      blue: '#005FCC',
      blueHover: '#004FA8',
      bluePressed: '#003D85',
      teal: '#007F82',
      tealSoft: '#E1F5F2',
    },
    lvp: {
      navy: '#001B44',
      navyRaised: '#073968',
      gold: '#C58A16',
      goldHover: '#BE8313',
      goldPressed: '#B57E12',
      goldSoft: '#FFF3DC',
      orange: '#FF6B00',
      orangeAction: '#B94700',
      orangeHover: '#9F3D00',
      orangePressed: '#843200',
      orangeSoft: '#FFF0E5',
      portalBlue: '#005FCC',
      portalBlueHover: '#004FA8',
      portalBluePressed: '#003D85',
    },
  },
  neutral: {
    white: '#FFFFFF',
    canvas: '#F3F8FC',
    subtle: '#F8FAFC',
    text: '#273444',
    muted: '#52647A',
    border: '#D6E3EF',
    controlBorder: '#7B8FA6',
    disabled: '#E5EAF0',
    disabledText: '#52647A',
  },
  folder: { surface: '#E7F3FF', hover: '#D8EBFF', border: '#B9D7F4' },
  status: {
    success: '#157347',
    successSoft: '#DCF4E5',
    warning: '#8A5700',
    warningSoft: '#FFF0C2',
    danger: '#C9142D',
    dangerSoft: '#FDE8EC',
    info: '#005FCC',
    infoSoft: '#E7F3FF',
  },
  business: { actionItems: '#FFF8D6', actionItemsBorder: '#E5CC72', actionItemsText: '#273444' },
  overlay: 'rgba(0, 27, 54, 0.55)',
  typography: {
    sans: 'Arial, Helvetica, sans-serif',
    display: 'Georgia, "Times New Roman", serif',
    size: {
      xs: '0.75rem',
      sm: '0.875rem',
      base: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
      '2xl': '1.5rem',
      '3xl': '2rem',
      '4xl': '2.5rem',
      '5xl': '3rem',
      '6xl': '4rem',
    },
    lineHeight: {
      xs: 1.5,
      sm: 1.5,
      base: 1.5,
      lg: 1.5,
      xl: 1.3,
      '2xl': 1.25,
      '3xl': 1.2,
      '4xl': 1.15,
      '5xl': 1.1,
      '6xl': 1.1,
    },
    weight: { regular: 400, medium: 500, semibold: 600, bold: 700 },
    eyebrowTracking: '0.12em',
  },
  spacing: {
    '0': '0rem',
    '0-5': '0.125rem',
    '1': '0.25rem',
    '2': '0.5rem',
    '3': '0.75rem',
    '4': '1rem',
    '5': '1.25rem',
    '6': '1.5rem',
    '8': '2rem',
    '10': '2.5rem',
    '12': '3rem',
    '16': '4rem',
  },
  radius: { none: '0', sm: '4px', md: '6px', lg: '8px', xl: '12px', pill: '9999px' },
  shadow: {
    none: 'none',
    sm: '0 1px 3px rgba(0, 27, 54, 0.08)',
    md: '0 4px 12px rgba(0, 27, 54, 0.10)',
    lg: '0 12px 32px rgba(0, 27, 54, 0.18)',
  },
  breakpoint: {
    base: '0px',
    sm: '640px',
    md: '768px',
    lg: '1024px',
    xl: '1280px',
    '2xl': '1536px',
  },
  layout: {
    sidebar: '240px',
    header: '64px',
    content: '1280px',
    public: '1120px',
    auth: '480px',
    modal: '640px',
    compactControl: '36px',
    control: '44px',
    largeControl: '48px',
    border: '1px',
    focus: '2px',
  },
} as const;

const platform = tokens.palettes.firmivra;
const lvp = tokens.palettes.lvp;
export const themes = {
  firmivra: {
    navigation: platform.navy,
    navigationHover: platform.navyRaised,
    heading: platform.navy,
    action: platform.blue,
    actionHover: platform.blueHover,
    actionPressed: platform.bluePressed,
    onAction: tokens.neutral.white,
    link: platform.blue,
    focus: platform.blue,
    accent: platform.teal,
    accentSoft: platform.tealSoft,
    publicAction: platform.blue,
    publicActionHover: platform.blueHover,
    publicActionPressed: platform.bluePressed,
    onPublicAction: tokens.neutral.white,
  },
  lvpPortal: {
    navigation: lvp.navy,
    navigationHover: lvp.navyRaised,
    heading: lvp.navy,
    action: lvp.portalBlue,
    actionHover: lvp.portalBlueHover,
    actionPressed: lvp.portalBluePressed,
    onAction: tokens.neutral.white,
    link: lvp.portalBlue,
    focus: lvp.portalBlue,
    accent: lvp.gold,
    accentSoft: lvp.goldSoft,
    publicAction: lvp.gold,
    publicActionHover: lvp.goldHover,
    publicActionPressed: lvp.goldPressed,
    onPublicAction: lvp.navy,
  },
  lvpBeginOnline: {
    navigation: lvp.navy,
    navigationHover: lvp.navyRaised,
    heading: lvp.navy,
    action: lvp.orangeAction,
    actionHover: lvp.orangeHover,
    actionPressed: lvp.orangePressed,
    onAction: tokens.neutral.white,
    link: lvp.portalBlue,
    focus: lvp.portalBlue,
    accent: lvp.orange,
    accentSoft: lvp.orangeSoft,
    publicAction: lvp.orangeAction,
    publicActionHover: lvp.orangeHover,
    publicActionPressed: lvp.orangePressed,
    onPublicAction: tokens.neutral.white,
  },
} as const;
export type ThemeName = keyof typeof themes;
